language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm test

after_script: "echo 'SENDING COVERALLS DATA' && cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
