language: node_js

node_js:
  - "v8.11.1"

before_install:
  - yarn global add postcss-cli

install:
  - yarn install

script:
  - yarn build

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
